language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
# install: "pip install -r requirements.txt"
install: "python setup.py develop"
# command to run tests
script: "python setup.py test"